// flow-typed signature: dea811179ccc8966d1137921533b5834
// flow-typed version: <<STUB>>/babel-watch_v2.0.7/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-watch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-watch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-watch/babel-watch' {
  declare module.exports: any;
}

declare module 'babel-watch/runner' {
  declare module.exports: any;
}

declare module 'babel-watch/TestProjects/a/src/api/facets' {
  declare module.exports: any;
}

declare module 'babel-watch/TestProjects/a/src/api/index' {
  declare module.exports: any;
}

declare module 'babel-watch/TestProjects/a/src/db' {
  declare module.exports: any;
}

declare module 'babel-watch/TestProjects/a/src/index' {
  declare module.exports: any;
}

declare module 'babel-watch/TestProjects/a/src/lib/util' {
  declare module.exports: any;
}

declare module 'babel-watch/TestProjects/a/src/middleware/index' {
  declare module.exports: any;
}

declare module 'babel-watch/TestProjects/a/src/models/facets' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-watch/babel-watch.js' {
  declare module.exports: $Exports<'babel-watch/babel-watch'>;
}
declare module 'babel-watch/runner.js' {
  declare module.exports: $Exports<'babel-watch/runner'>;
}
declare module 'babel-watch/TestProjects/a/src/api/facets.js' {
  declare module.exports: $Exports<'babel-watch/TestProjects/a/src/api/facets'>;
}
declare module 'babel-watch/TestProjects/a/src/api/index.js' {
  declare module.exports: $Exports<'babel-watch/TestProjects/a/src/api/index'>;
}
declare module 'babel-watch/TestProjects/a/src/db.js' {
  declare module.exports: $Exports<'babel-watch/TestProjects/a/src/db'>;
}
declare module 'babel-watch/TestProjects/a/src/index.js' {
  declare module.exports: $Exports<'babel-watch/TestProjects/a/src/index'>;
}
declare module 'babel-watch/TestProjects/a/src/lib/util.js' {
  declare module.exports: $Exports<'babel-watch/TestProjects/a/src/lib/util'>;
}
declare module 'babel-watch/TestProjects/a/src/middleware/index.js' {
  declare module.exports: $Exports<'babel-watch/TestProjects/a/src/middleware/index'>;
}
declare module 'babel-watch/TestProjects/a/src/models/facets.js' {
  declare module.exports: $Exports<'babel-watch/TestProjects/a/src/models/facets'>;
}
