// flow-typed signature: 19444c3bc4ee32e850c65cf291c5ea65
// flow-typed version: <<STUB>>/bootstrap_v^4.0.0-beta.2/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bootstrap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bootstrap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bootstrap/build/change-version' {
  declare module.exports: any;
}

declare module 'bootstrap/build/htmllint' {
  declare module.exports: any;
}

declare module 'bootstrap/build/postcss.config' {
  declare module.exports: any;
}

declare module 'bootstrap/build/rollup.config' {
  declare module.exports: any;
}

declare module 'bootstrap/build/saucelabs-unit-test' {
  declare module.exports: any;
}

declare module 'bootstrap/build/workbox' {
  declare module.exports: any;
}

declare module 'bootstrap/dist/js/bootstrap.bundle' {
  declare module.exports: any;
}

declare module 'bootstrap/dist/js/bootstrap.bundle.min' {
  declare module.exports: any;
}

declare module 'bootstrap/dist/js/bootstrap' {
  declare module.exports: any;
}

declare module 'bootstrap/dist/js/bootstrap.min' {
  declare module.exports: any;
}

declare module 'bootstrap/js/dist/alert' {
  declare module.exports: any;
}

declare module 'bootstrap/js/dist/button' {
  declare module.exports: any;
}

declare module 'bootstrap/js/dist/carousel' {
  declare module.exports: any;
}

declare module 'bootstrap/js/dist/collapse' {
  declare module.exports: any;
}

declare module 'bootstrap/js/dist/dropdown' {
  declare module.exports: any;
}

declare module 'bootstrap/js/dist/index' {
  declare module.exports: any;
}

declare module 'bootstrap/js/dist/modal' {
  declare module.exports: any;
}

declare module 'bootstrap/js/dist/popover' {
  declare module.exports: any;
}

declare module 'bootstrap/js/dist/scrollspy' {
  declare module.exports: any;
}

declare module 'bootstrap/js/dist/tab' {
  declare module.exports: any;
}

declare module 'bootstrap/js/dist/tooltip' {
  declare module.exports: any;
}

declare module 'bootstrap/js/dist/util' {
  declare module.exports: any;
}

declare module 'bootstrap/js/src/alert' {
  declare module.exports: any;
}

declare module 'bootstrap/js/src/button' {
  declare module.exports: any;
}

declare module 'bootstrap/js/src/carousel' {
  declare module.exports: any;
}

declare module 'bootstrap/js/src/collapse' {
  declare module.exports: any;
}

declare module 'bootstrap/js/src/dropdown' {
  declare module.exports: any;
}

declare module 'bootstrap/js/src/index' {
  declare module.exports: any;
}

declare module 'bootstrap/js/src/modal' {
  declare module.exports: any;
}

declare module 'bootstrap/js/src/popover' {
  declare module.exports: any;
}

declare module 'bootstrap/js/src/scrollspy' {
  declare module.exports: any;
}

declare module 'bootstrap/js/src/tab' {
  declare module.exports: any;
}

declare module 'bootstrap/js/src/tooltip' {
  declare module.exports: any;
}

declare module 'bootstrap/js/src/util' {
  declare module.exports: any;
}

declare module 'bootstrap/js/tests/unit/alert' {
  declare module.exports: any;
}

declare module 'bootstrap/js/tests/unit/button' {
  declare module.exports: any;
}

declare module 'bootstrap/js/tests/unit/carousel' {
  declare module.exports: any;
}

declare module 'bootstrap/js/tests/unit/collapse' {
  declare module.exports: any;
}

declare module 'bootstrap/js/tests/unit/dropdown' {
  declare module.exports: any;
}

declare module 'bootstrap/js/tests/unit/modal' {
  declare module.exports: any;
}

declare module 'bootstrap/js/tests/unit/popover' {
  declare module.exports: any;
}

declare module 'bootstrap/js/tests/unit/scrollspy' {
  declare module.exports: any;
}

declare module 'bootstrap/js/tests/unit/tab' {
  declare module.exports: any;
}

declare module 'bootstrap/js/tests/unit/tooltip' {
  declare module.exports: any;
}

declare module 'bootstrap/js/tests/vendor/qunit' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bootstrap/build/change-version.js' {
  declare module.exports: $Exports<'bootstrap/build/change-version'>;
}
declare module 'bootstrap/build/htmllint.js' {
  declare module.exports: $Exports<'bootstrap/build/htmllint'>;
}
declare module 'bootstrap/build/postcss.config.js' {
  declare module.exports: $Exports<'bootstrap/build/postcss.config'>;
}
declare module 'bootstrap/build/rollup.config.js' {
  declare module.exports: $Exports<'bootstrap/build/rollup.config'>;
}
declare module 'bootstrap/build/saucelabs-unit-test.js' {
  declare module.exports: $Exports<'bootstrap/build/saucelabs-unit-test'>;
}
declare module 'bootstrap/build/workbox.js' {
  declare module.exports: $Exports<'bootstrap/build/workbox'>;
}
declare module 'bootstrap/dist/js/bootstrap.bundle.js' {
  declare module.exports: $Exports<'bootstrap/dist/js/bootstrap.bundle'>;
}
declare module 'bootstrap/dist/js/bootstrap.bundle.min.js' {
  declare module.exports: $Exports<'bootstrap/dist/js/bootstrap.bundle.min'>;
}
declare module 'bootstrap/dist/js/bootstrap.js' {
  declare module.exports: $Exports<'bootstrap/dist/js/bootstrap'>;
}
declare module 'bootstrap/dist/js/bootstrap.min.js' {
  declare module.exports: $Exports<'bootstrap/dist/js/bootstrap.min'>;
}
declare module 'bootstrap/js/dist/alert.js' {
  declare module.exports: $Exports<'bootstrap/js/dist/alert'>;
}
declare module 'bootstrap/js/dist/button.js' {
  declare module.exports: $Exports<'bootstrap/js/dist/button'>;
}
declare module 'bootstrap/js/dist/carousel.js' {
  declare module.exports: $Exports<'bootstrap/js/dist/carousel'>;
}
declare module 'bootstrap/js/dist/collapse.js' {
  declare module.exports: $Exports<'bootstrap/js/dist/collapse'>;
}
declare module 'bootstrap/js/dist/dropdown.js' {
  declare module.exports: $Exports<'bootstrap/js/dist/dropdown'>;
}
declare module 'bootstrap/js/dist/index.js' {
  declare module.exports: $Exports<'bootstrap/js/dist/index'>;
}
declare module 'bootstrap/js/dist/modal.js' {
  declare module.exports: $Exports<'bootstrap/js/dist/modal'>;
}
declare module 'bootstrap/js/dist/popover.js' {
  declare module.exports: $Exports<'bootstrap/js/dist/popover'>;
}
declare module 'bootstrap/js/dist/scrollspy.js' {
  declare module.exports: $Exports<'bootstrap/js/dist/scrollspy'>;
}
declare module 'bootstrap/js/dist/tab.js' {
  declare module.exports: $Exports<'bootstrap/js/dist/tab'>;
}
declare module 'bootstrap/js/dist/tooltip.js' {
  declare module.exports: $Exports<'bootstrap/js/dist/tooltip'>;
}
declare module 'bootstrap/js/dist/util.js' {
  declare module.exports: $Exports<'bootstrap/js/dist/util'>;
}
declare module 'bootstrap/js/src/alert.js' {
  declare module.exports: $Exports<'bootstrap/js/src/alert'>;
}
declare module 'bootstrap/js/src/button.js' {
  declare module.exports: $Exports<'bootstrap/js/src/button'>;
}
declare module 'bootstrap/js/src/carousel.js' {
  declare module.exports: $Exports<'bootstrap/js/src/carousel'>;
}
declare module 'bootstrap/js/src/collapse.js' {
  declare module.exports: $Exports<'bootstrap/js/src/collapse'>;
}
declare module 'bootstrap/js/src/dropdown.js' {
  declare module.exports: $Exports<'bootstrap/js/src/dropdown'>;
}
declare module 'bootstrap/js/src/index.js' {
  declare module.exports: $Exports<'bootstrap/js/src/index'>;
}
declare module 'bootstrap/js/src/modal.js' {
  declare module.exports: $Exports<'bootstrap/js/src/modal'>;
}
declare module 'bootstrap/js/src/popover.js' {
  declare module.exports: $Exports<'bootstrap/js/src/popover'>;
}
declare module 'bootstrap/js/src/scrollspy.js' {
  declare module.exports: $Exports<'bootstrap/js/src/scrollspy'>;
}
declare module 'bootstrap/js/src/tab.js' {
  declare module.exports: $Exports<'bootstrap/js/src/tab'>;
}
declare module 'bootstrap/js/src/tooltip.js' {
  declare module.exports: $Exports<'bootstrap/js/src/tooltip'>;
}
declare module 'bootstrap/js/src/util.js' {
  declare module.exports: $Exports<'bootstrap/js/src/util'>;
}
declare module 'bootstrap/js/tests/unit/alert.js' {
  declare module.exports: $Exports<'bootstrap/js/tests/unit/alert'>;
}
declare module 'bootstrap/js/tests/unit/button.js' {
  declare module.exports: $Exports<'bootstrap/js/tests/unit/button'>;
}
declare module 'bootstrap/js/tests/unit/carousel.js' {
  declare module.exports: $Exports<'bootstrap/js/tests/unit/carousel'>;
}
declare module 'bootstrap/js/tests/unit/collapse.js' {
  declare module.exports: $Exports<'bootstrap/js/tests/unit/collapse'>;
}
declare module 'bootstrap/js/tests/unit/dropdown.js' {
  declare module.exports: $Exports<'bootstrap/js/tests/unit/dropdown'>;
}
declare module 'bootstrap/js/tests/unit/modal.js' {
  declare module.exports: $Exports<'bootstrap/js/tests/unit/modal'>;
}
declare module 'bootstrap/js/tests/unit/popover.js' {
  declare module.exports: $Exports<'bootstrap/js/tests/unit/popover'>;
}
declare module 'bootstrap/js/tests/unit/scrollspy.js' {
  declare module.exports: $Exports<'bootstrap/js/tests/unit/scrollspy'>;
}
declare module 'bootstrap/js/tests/unit/tab.js' {
  declare module.exports: $Exports<'bootstrap/js/tests/unit/tab'>;
}
declare module 'bootstrap/js/tests/unit/tooltip.js' {
  declare module.exports: $Exports<'bootstrap/js/tests/unit/tooltip'>;
}
declare module 'bootstrap/js/tests/vendor/qunit.js' {
  declare module.exports: $Exports<'bootstrap/js/tests/vendor/qunit'>;
}
