// flow-typed signature: 174539fea8c0c83cd580c4afd0e0df52
// flow-typed version: <<STUB>>/flow-webpack-plugin_v1.2.0/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flow-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'flow-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'flow-webpack-plugin/dist/index' {
  declare module.exports: any;
}

declare module 'flow-webpack-plugin/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'flow-webpack-plugin/dist/index.js' {
  declare module.exports: $Exports<'flow-webpack-plugin/dist/index'>;
}
declare module 'flow-webpack-plugin/src/index.js' {
  declare module.exports: $Exports<'flow-webpack-plugin/src/index'>;
}
