// flow-typed signature: 9270f4d47d3a88ecbe3565e13b1a0516
// flow-typed version: <<STUB>>/http-auth_v^3.2.3/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'http-auth'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'http-auth' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'http-auth/src/auth/base' {
  declare module.exports: any;
}

declare module 'http-auth/src/auth/basic' {
  declare module.exports: any;
}

declare module 'http-auth/src/auth/digest' {
  declare module.exports: any;
}

declare module 'http-auth/src/auth/utils' {
  declare module.exports: any;
}

declare module 'http-auth/src/http-auth' {
  declare module.exports: any;
}

declare module 'http-auth/src/server/connect' {
  declare module.exports: any;
}

declare module 'http-auth/src/server/hapi' {
  declare module.exports: any;
}

declare module 'http-auth/src/server/http' {
  declare module.exports: any;
}

declare module 'http-auth/src/server/https' {
  declare module.exports: any;
}

declare module 'http-auth/src/server/koa' {
  declare module.exports: any;
}

declare module 'http-auth/src/server/passport' {
  declare module.exports: any;
}

declare module 'http-auth/src/server/proxy' {
  declare module.exports: any;
}

// Filename aliases
declare module 'http-auth/src/auth/base.js' {
  declare module.exports: $Exports<'http-auth/src/auth/base'>;
}
declare module 'http-auth/src/auth/basic.js' {
  declare module.exports: $Exports<'http-auth/src/auth/basic'>;
}
declare module 'http-auth/src/auth/digest.js' {
  declare module.exports: $Exports<'http-auth/src/auth/digest'>;
}
declare module 'http-auth/src/auth/utils.js' {
  declare module.exports: $Exports<'http-auth/src/auth/utils'>;
}
declare module 'http-auth/src/http-auth.js' {
  declare module.exports: $Exports<'http-auth/src/http-auth'>;
}
declare module 'http-auth/src/server/connect.js' {
  declare module.exports: $Exports<'http-auth/src/server/connect'>;
}
declare module 'http-auth/src/server/hapi.js' {
  declare module.exports: $Exports<'http-auth/src/server/hapi'>;
}
declare module 'http-auth/src/server/http.js' {
  declare module.exports: $Exports<'http-auth/src/server/http'>;
}
declare module 'http-auth/src/server/https.js' {
  declare module.exports: $Exports<'http-auth/src/server/https'>;
}
declare module 'http-auth/src/server/koa.js' {
  declare module.exports: $Exports<'http-auth/src/server/koa'>;
}
declare module 'http-auth/src/server/passport.js' {
  declare module.exports: $Exports<'http-auth/src/server/passport'>;
}
declare module 'http-auth/src/server/proxy.js' {
  declare module.exports: $Exports<'http-auth/src/server/proxy'>;
}
