// flow-typed signature: 00e50190862301f3249e3780e74dc40f
// flow-typed version: <<STUB>>/react-animations_v^1.0.0/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-animations'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-animations' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-animations/dist/react-animations' {
  declare module.exports: any;
}

declare module 'react-animations/dist/react-animations.min' {
  declare module.exports: any;
}

declare module 'react-animations/lib/bouceOut' {
  declare module.exports: any;
}

declare module 'react-animations/lib/bounce-in-down' {
  declare module.exports: any;
}

declare module 'react-animations/lib/bounce-in-left' {
  declare module.exports: any;
}

declare module 'react-animations/lib/bounce-in-right' {
  declare module.exports: any;
}

declare module 'react-animations/lib/bounce-in-up' {
  declare module.exports: any;
}

declare module 'react-animations/lib/bounce-in' {
  declare module.exports: any;
}

declare module 'react-animations/lib/bounce-out-down' {
  declare module.exports: any;
}

declare module 'react-animations/lib/bounce-out-left' {
  declare module.exports: any;
}

declare module 'react-animations/lib/bounce-out-right' {
  declare module.exports: any;
}

declare module 'react-animations/lib/bounce-out-up' {
  declare module.exports: any;
}

declare module 'react-animations/lib/bounce-out' {
  declare module.exports: any;
}

declare module 'react-animations/lib/bounce' {
  declare module.exports: any;
}

declare module 'react-animations/lib/bounceIn' {
  declare module.exports: any;
}

declare module 'react-animations/lib/bounceInDown' {
  declare module.exports: any;
}

declare module 'react-animations/lib/bounceInLeft' {
  declare module.exports: any;
}

declare module 'react-animations/lib/bounceInRight' {
  declare module.exports: any;
}

declare module 'react-animations/lib/bounceInUp' {
  declare module.exports: any;
}

declare module 'react-animations/lib/bounceOut' {
  declare module.exports: any;
}

declare module 'react-animations/lib/bounceOutDown' {
  declare module.exports: any;
}

declare module 'react-animations/lib/bounceOutLeft' {
  declare module.exports: any;
}

declare module 'react-animations/lib/bounceOutRight' {
  declare module.exports: any;
}

declare module 'react-animations/lib/bounceOutUp' {
  declare module.exports: any;
}

declare module 'react-animations/lib/fade-in-down-big' {
  declare module.exports: any;
}

declare module 'react-animations/lib/fade-in-down' {
  declare module.exports: any;
}

declare module 'react-animations/lib/fade-in-left-big' {
  declare module.exports: any;
}

declare module 'react-animations/lib/fade-in-left' {
  declare module.exports: any;
}

declare module 'react-animations/lib/fade-in-right-big' {
  declare module.exports: any;
}

declare module 'react-animations/lib/fade-in-right' {
  declare module.exports: any;
}

declare module 'react-animations/lib/fade-in-up-big' {
  declare module.exports: any;
}

declare module 'react-animations/lib/fade-in-up' {
  declare module.exports: any;
}

declare module 'react-animations/lib/fade-in' {
  declare module.exports: any;
}

declare module 'react-animations/lib/fade-out-down-big' {
  declare module.exports: any;
}

declare module 'react-animations/lib/fade-out-down' {
  declare module.exports: any;
}

declare module 'react-animations/lib/fade-out-left-big' {
  declare module.exports: any;
}

declare module 'react-animations/lib/fade-out-left' {
  declare module.exports: any;
}

declare module 'react-animations/lib/fade-out-right-big' {
  declare module.exports: any;
}

declare module 'react-animations/lib/fade-out-right' {
  declare module.exports: any;
}

declare module 'react-animations/lib/fade-out-up-big' {
  declare module.exports: any;
}

declare module 'react-animations/lib/fade-out-up' {
  declare module.exports: any;
}

declare module 'react-animations/lib/fade-out' {
  declare module.exports: any;
}

declare module 'react-animations/lib/fadeIn' {
  declare module.exports: any;
}

declare module 'react-animations/lib/fadeInDown' {
  declare module.exports: any;
}

declare module 'react-animations/lib/fadeInDownBig' {
  declare module.exports: any;
}

declare module 'react-animations/lib/fadeInLeft' {
  declare module.exports: any;
}

declare module 'react-animations/lib/fadeInLeftBig' {
  declare module.exports: any;
}

declare module 'react-animations/lib/fadeInRight' {
  declare module.exports: any;
}

declare module 'react-animations/lib/fadeInRightBig' {
  declare module.exports: any;
}

declare module 'react-animations/lib/fadeInUp' {
  declare module.exports: any;
}

declare module 'react-animations/lib/fadeInUpBig' {
  declare module.exports: any;
}

declare module 'react-animations/lib/fadeOut' {
  declare module.exports: any;
}

declare module 'react-animations/lib/fadeOutDown' {
  declare module.exports: any;
}

declare module 'react-animations/lib/fadeOutDownBig' {
  declare module.exports: any;
}

declare module 'react-animations/lib/fadeOutLeft' {
  declare module.exports: any;
}

declare module 'react-animations/lib/fadeOutLeftBig' {
  declare module.exports: any;
}

declare module 'react-animations/lib/fadeOutRight' {
  declare module.exports: any;
}

declare module 'react-animations/lib/fadeOutRightBig' {
  declare module.exports: any;
}

declare module 'react-animations/lib/fadeOutUp' {
  declare module.exports: any;
}

declare module 'react-animations/lib/fadeOutUpBig' {
  declare module.exports: any;
}

declare module 'react-animations/lib/flash' {
  declare module.exports: any;
}

declare module 'react-animations/lib/flip-in-x' {
  declare module.exports: any;
}

declare module 'react-animations/lib/flip-in-y' {
  declare module.exports: any;
}

declare module 'react-animations/lib/flip-out-x' {
  declare module.exports: any;
}

declare module 'react-animations/lib/flip-out-y' {
  declare module.exports: any;
}

declare module 'react-animations/lib/flip' {
  declare module.exports: any;
}

declare module 'react-animations/lib/flipInX' {
  declare module.exports: any;
}

declare module 'react-animations/lib/flipInY' {
  declare module.exports: any;
}

declare module 'react-animations/lib/flipOutX' {
  declare module.exports: any;
}

declare module 'react-animations/lib/flipOutY' {
  declare module.exports: any;
}

declare module 'react-animations/lib/head-shake' {
  declare module.exports: any;
}

declare module 'react-animations/lib/headShake' {
  declare module.exports: any;
}

declare module 'react-animations/lib/hinge' {
  declare module.exports: any;
}

declare module 'react-animations/lib/index' {
  declare module.exports: any;
}

declare module 'react-animations/lib/jello' {
  declare module.exports: any;
}

declare module 'react-animations/lib/light-speed-in' {
  declare module.exports: any;
}

declare module 'react-animations/lib/light-speed-out' {
  declare module.exports: any;
}

declare module 'react-animations/lib/lightSpeedIn' {
  declare module.exports: any;
}

declare module 'react-animations/lib/lightSpeedOut' {
  declare module.exports: any;
}

declare module 'react-animations/lib/merge' {
  declare module.exports: any;
}

declare module 'react-animations/lib/pulse' {
  declare module.exports: any;
}

declare module 'react-animations/lib/roll-in' {
  declare module.exports: any;
}

declare module 'react-animations/lib/roll-out' {
  declare module.exports: any;
}

declare module 'react-animations/lib/rollIn' {
  declare module.exports: any;
}

declare module 'react-animations/lib/rollOut' {
  declare module.exports: any;
}

declare module 'react-animations/lib/rotate-in-down-left' {
  declare module.exports: any;
}

declare module 'react-animations/lib/rotate-in-down-right' {
  declare module.exports: any;
}

declare module 'react-animations/lib/rotate-in-up-left' {
  declare module.exports: any;
}

declare module 'react-animations/lib/rotate-in-up-right' {
  declare module.exports: any;
}

declare module 'react-animations/lib/rotate-in' {
  declare module.exports: any;
}

declare module 'react-animations/lib/rotate-out-down-left' {
  declare module.exports: any;
}

declare module 'react-animations/lib/rotate-out-down-right' {
  declare module.exports: any;
}

declare module 'react-animations/lib/rotate-out-up-left' {
  declare module.exports: any;
}

declare module 'react-animations/lib/rotate-out-up-right' {
  declare module.exports: any;
}

declare module 'react-animations/lib/rotate-out' {
  declare module.exports: any;
}

declare module 'react-animations/lib/rotateIn' {
  declare module.exports: any;
}

declare module 'react-animations/lib/rotateInDownLeft' {
  declare module.exports: any;
}

declare module 'react-animations/lib/rotateInDownRight' {
  declare module.exports: any;
}

declare module 'react-animations/lib/rotateInUpLeft' {
  declare module.exports: any;
}

declare module 'react-animations/lib/rotateInUpRight' {
  declare module.exports: any;
}

declare module 'react-animations/lib/rotateOut' {
  declare module.exports: any;
}

declare module 'react-animations/lib/rotateOutDownLeft' {
  declare module.exports: any;
}

declare module 'react-animations/lib/rotateOutDownRight' {
  declare module.exports: any;
}

declare module 'react-animations/lib/rotateOutUpLeft' {
  declare module.exports: any;
}

declare module 'react-animations/lib/rotateOutUpRight' {
  declare module.exports: any;
}

declare module 'react-animations/lib/rubber-band' {
  declare module.exports: any;
}

declare module 'react-animations/lib/rubberBand' {
  declare module.exports: any;
}

declare module 'react-animations/lib/shake' {
  declare module.exports: any;
}

declare module 'react-animations/lib/slide-in-down' {
  declare module.exports: any;
}

declare module 'react-animations/lib/slide-in-left' {
  declare module.exports: any;
}

declare module 'react-animations/lib/slide-in-right' {
  declare module.exports: any;
}

declare module 'react-animations/lib/slide-in-up' {
  declare module.exports: any;
}

declare module 'react-animations/lib/slide-out-down' {
  declare module.exports: any;
}

declare module 'react-animations/lib/slide-out-left' {
  declare module.exports: any;
}

declare module 'react-animations/lib/slide-out-right' {
  declare module.exports: any;
}

declare module 'react-animations/lib/slide-out-up' {
  declare module.exports: any;
}

declare module 'react-animations/lib/slideInDown' {
  declare module.exports: any;
}

declare module 'react-animations/lib/slideInLeft' {
  declare module.exports: any;
}

declare module 'react-animations/lib/slideInRight' {
  declare module.exports: any;
}

declare module 'react-animations/lib/slideInUp' {
  declare module.exports: any;
}

declare module 'react-animations/lib/slideOutDown' {
  declare module.exports: any;
}

declare module 'react-animations/lib/slideOutLeft' {
  declare module.exports: any;
}

declare module 'react-animations/lib/slideOutRight' {
  declare module.exports: any;
}

declare module 'react-animations/lib/slideOutUp' {
  declare module.exports: any;
}

declare module 'react-animations/lib/swing' {
  declare module.exports: any;
}

declare module 'react-animations/lib/tada' {
  declare module.exports: any;
}

declare module 'react-animations/lib/types' {
  declare module.exports: any;
}

declare module 'react-animations/lib/utils' {
  declare module.exports: any;
}

declare module 'react-animations/lib/wobble' {
  declare module.exports: any;
}

declare module 'react-animations/lib/zoom-in-down' {
  declare module.exports: any;
}

declare module 'react-animations/lib/zoom-in-left' {
  declare module.exports: any;
}

declare module 'react-animations/lib/zoom-in-right' {
  declare module.exports: any;
}

declare module 'react-animations/lib/zoom-in-up' {
  declare module.exports: any;
}

declare module 'react-animations/lib/zoom-in' {
  declare module.exports: any;
}

declare module 'react-animations/lib/zoom-out-down' {
  declare module.exports: any;
}

declare module 'react-animations/lib/zoom-out-left' {
  declare module.exports: any;
}

declare module 'react-animations/lib/zoom-out-right' {
  declare module.exports: any;
}

declare module 'react-animations/lib/zoom-out-up' {
  declare module.exports: any;
}

declare module 'react-animations/lib/zoom-out' {
  declare module.exports: any;
}

declare module 'react-animations/lib/zoomIn' {
  declare module.exports: any;
}

declare module 'react-animations/lib/zoomInDown' {
  declare module.exports: any;
}

declare module 'react-animations/lib/zoomInLeft' {
  declare module.exports: any;
}

declare module 'react-animations/lib/zoomInRight' {
  declare module.exports: any;
}

declare module 'react-animations/lib/zoomInUp' {
  declare module.exports: any;
}

declare module 'react-animations/lib/zoomOut' {
  declare module.exports: any;
}

declare module 'react-animations/lib/zoomOutDown' {
  declare module.exports: any;
}

declare module 'react-animations/lib/zoomOutLeft' {
  declare module.exports: any;
}

declare module 'react-animations/lib/zoomOutRight' {
  declare module.exports: any;
}

declare module 'react-animations/lib/zoomOutUp' {
  declare module.exports: any;
}

declare module 'react-animations/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-animations/dist/react-animations.js' {
  declare module.exports: $Exports<'react-animations/dist/react-animations'>;
}
declare module 'react-animations/dist/react-animations.min.js' {
  declare module.exports: $Exports<'react-animations/dist/react-animations.min'>;
}
declare module 'react-animations/lib/bouceOut.js' {
  declare module.exports: $Exports<'react-animations/lib/bouceOut'>;
}
declare module 'react-animations/lib/bounce-in-down.js' {
  declare module.exports: $Exports<'react-animations/lib/bounce-in-down'>;
}
declare module 'react-animations/lib/bounce-in-left.js' {
  declare module.exports: $Exports<'react-animations/lib/bounce-in-left'>;
}
declare module 'react-animations/lib/bounce-in-right.js' {
  declare module.exports: $Exports<'react-animations/lib/bounce-in-right'>;
}
declare module 'react-animations/lib/bounce-in-up.js' {
  declare module.exports: $Exports<'react-animations/lib/bounce-in-up'>;
}
declare module 'react-animations/lib/bounce-in.js' {
  declare module.exports: $Exports<'react-animations/lib/bounce-in'>;
}
declare module 'react-animations/lib/bounce-out-down.js' {
  declare module.exports: $Exports<'react-animations/lib/bounce-out-down'>;
}
declare module 'react-animations/lib/bounce-out-left.js' {
  declare module.exports: $Exports<'react-animations/lib/bounce-out-left'>;
}
declare module 'react-animations/lib/bounce-out-right.js' {
  declare module.exports: $Exports<'react-animations/lib/bounce-out-right'>;
}
declare module 'react-animations/lib/bounce-out-up.js' {
  declare module.exports: $Exports<'react-animations/lib/bounce-out-up'>;
}
declare module 'react-animations/lib/bounce-out.js' {
  declare module.exports: $Exports<'react-animations/lib/bounce-out'>;
}
declare module 'react-animations/lib/bounce.js' {
  declare module.exports: $Exports<'react-animations/lib/bounce'>;
}
declare module 'react-animations/lib/bounceIn.js' {
  declare module.exports: $Exports<'react-animations/lib/bounceIn'>;
}
declare module 'react-animations/lib/bounceInDown.js' {
  declare module.exports: $Exports<'react-animations/lib/bounceInDown'>;
}
declare module 'react-animations/lib/bounceInLeft.js' {
  declare module.exports: $Exports<'react-animations/lib/bounceInLeft'>;
}
declare module 'react-animations/lib/bounceInRight.js' {
  declare module.exports: $Exports<'react-animations/lib/bounceInRight'>;
}
declare module 'react-animations/lib/bounceInUp.js' {
  declare module.exports: $Exports<'react-animations/lib/bounceInUp'>;
}
declare module 'react-animations/lib/bounceOut.js' {
  declare module.exports: $Exports<'react-animations/lib/bounceOut'>;
}
declare module 'react-animations/lib/bounceOutDown.js' {
  declare module.exports: $Exports<'react-animations/lib/bounceOutDown'>;
}
declare module 'react-animations/lib/bounceOutLeft.js' {
  declare module.exports: $Exports<'react-animations/lib/bounceOutLeft'>;
}
declare module 'react-animations/lib/bounceOutRight.js' {
  declare module.exports: $Exports<'react-animations/lib/bounceOutRight'>;
}
declare module 'react-animations/lib/bounceOutUp.js' {
  declare module.exports: $Exports<'react-animations/lib/bounceOutUp'>;
}
declare module 'react-animations/lib/fade-in-down-big.js' {
  declare module.exports: $Exports<'react-animations/lib/fade-in-down-big'>;
}
declare module 'react-animations/lib/fade-in-down.js' {
  declare module.exports: $Exports<'react-animations/lib/fade-in-down'>;
}
declare module 'react-animations/lib/fade-in-left-big.js' {
  declare module.exports: $Exports<'react-animations/lib/fade-in-left-big'>;
}
declare module 'react-animations/lib/fade-in-left.js' {
  declare module.exports: $Exports<'react-animations/lib/fade-in-left'>;
}
declare module 'react-animations/lib/fade-in-right-big.js' {
  declare module.exports: $Exports<'react-animations/lib/fade-in-right-big'>;
}
declare module 'react-animations/lib/fade-in-right.js' {
  declare module.exports: $Exports<'react-animations/lib/fade-in-right'>;
}
declare module 'react-animations/lib/fade-in-up-big.js' {
  declare module.exports: $Exports<'react-animations/lib/fade-in-up-big'>;
}
declare module 'react-animations/lib/fade-in-up.js' {
  declare module.exports: $Exports<'react-animations/lib/fade-in-up'>;
}
declare module 'react-animations/lib/fade-in.js' {
  declare module.exports: $Exports<'react-animations/lib/fade-in'>;
}
declare module 'react-animations/lib/fade-out-down-big.js' {
  declare module.exports: $Exports<'react-animations/lib/fade-out-down-big'>;
}
declare module 'react-animations/lib/fade-out-down.js' {
  declare module.exports: $Exports<'react-animations/lib/fade-out-down'>;
}
declare module 'react-animations/lib/fade-out-left-big.js' {
  declare module.exports: $Exports<'react-animations/lib/fade-out-left-big'>;
}
declare module 'react-animations/lib/fade-out-left.js' {
  declare module.exports: $Exports<'react-animations/lib/fade-out-left'>;
}
declare module 'react-animations/lib/fade-out-right-big.js' {
  declare module.exports: $Exports<'react-animations/lib/fade-out-right-big'>;
}
declare module 'react-animations/lib/fade-out-right.js' {
  declare module.exports: $Exports<'react-animations/lib/fade-out-right'>;
}
declare module 'react-animations/lib/fade-out-up-big.js' {
  declare module.exports: $Exports<'react-animations/lib/fade-out-up-big'>;
}
declare module 'react-animations/lib/fade-out-up.js' {
  declare module.exports: $Exports<'react-animations/lib/fade-out-up'>;
}
declare module 'react-animations/lib/fade-out.js' {
  declare module.exports: $Exports<'react-animations/lib/fade-out'>;
}
declare module 'react-animations/lib/fadeIn.js' {
  declare module.exports: $Exports<'react-animations/lib/fadeIn'>;
}
declare module 'react-animations/lib/fadeInDown.js' {
  declare module.exports: $Exports<'react-animations/lib/fadeInDown'>;
}
declare module 'react-animations/lib/fadeInDownBig.js' {
  declare module.exports: $Exports<'react-animations/lib/fadeInDownBig'>;
}
declare module 'react-animations/lib/fadeInLeft.js' {
  declare module.exports: $Exports<'react-animations/lib/fadeInLeft'>;
}
declare module 'react-animations/lib/fadeInLeftBig.js' {
  declare module.exports: $Exports<'react-animations/lib/fadeInLeftBig'>;
}
declare module 'react-animations/lib/fadeInRight.js' {
  declare module.exports: $Exports<'react-animations/lib/fadeInRight'>;
}
declare module 'react-animations/lib/fadeInRightBig.js' {
  declare module.exports: $Exports<'react-animations/lib/fadeInRightBig'>;
}
declare module 'react-animations/lib/fadeInUp.js' {
  declare module.exports: $Exports<'react-animations/lib/fadeInUp'>;
}
declare module 'react-animations/lib/fadeInUpBig.js' {
  declare module.exports: $Exports<'react-animations/lib/fadeInUpBig'>;
}
declare module 'react-animations/lib/fadeOut.js' {
  declare module.exports: $Exports<'react-animations/lib/fadeOut'>;
}
declare module 'react-animations/lib/fadeOutDown.js' {
  declare module.exports: $Exports<'react-animations/lib/fadeOutDown'>;
}
declare module 'react-animations/lib/fadeOutDownBig.js' {
  declare module.exports: $Exports<'react-animations/lib/fadeOutDownBig'>;
}
declare module 'react-animations/lib/fadeOutLeft.js' {
  declare module.exports: $Exports<'react-animations/lib/fadeOutLeft'>;
}
declare module 'react-animations/lib/fadeOutLeftBig.js' {
  declare module.exports: $Exports<'react-animations/lib/fadeOutLeftBig'>;
}
declare module 'react-animations/lib/fadeOutRight.js' {
  declare module.exports: $Exports<'react-animations/lib/fadeOutRight'>;
}
declare module 'react-animations/lib/fadeOutRightBig.js' {
  declare module.exports: $Exports<'react-animations/lib/fadeOutRightBig'>;
}
declare module 'react-animations/lib/fadeOutUp.js' {
  declare module.exports: $Exports<'react-animations/lib/fadeOutUp'>;
}
declare module 'react-animations/lib/fadeOutUpBig.js' {
  declare module.exports: $Exports<'react-animations/lib/fadeOutUpBig'>;
}
declare module 'react-animations/lib/flash.js' {
  declare module.exports: $Exports<'react-animations/lib/flash'>;
}
declare module 'react-animations/lib/flip-in-x.js' {
  declare module.exports: $Exports<'react-animations/lib/flip-in-x'>;
}
declare module 'react-animations/lib/flip-in-y.js' {
  declare module.exports: $Exports<'react-animations/lib/flip-in-y'>;
}
declare module 'react-animations/lib/flip-out-x.js' {
  declare module.exports: $Exports<'react-animations/lib/flip-out-x'>;
}
declare module 'react-animations/lib/flip-out-y.js' {
  declare module.exports: $Exports<'react-animations/lib/flip-out-y'>;
}
declare module 'react-animations/lib/flip.js' {
  declare module.exports: $Exports<'react-animations/lib/flip'>;
}
declare module 'react-animations/lib/flipInX.js' {
  declare module.exports: $Exports<'react-animations/lib/flipInX'>;
}
declare module 'react-animations/lib/flipInY.js' {
  declare module.exports: $Exports<'react-animations/lib/flipInY'>;
}
declare module 'react-animations/lib/flipOutX.js' {
  declare module.exports: $Exports<'react-animations/lib/flipOutX'>;
}
declare module 'react-animations/lib/flipOutY.js' {
  declare module.exports: $Exports<'react-animations/lib/flipOutY'>;
}
declare module 'react-animations/lib/head-shake.js' {
  declare module.exports: $Exports<'react-animations/lib/head-shake'>;
}
declare module 'react-animations/lib/headShake.js' {
  declare module.exports: $Exports<'react-animations/lib/headShake'>;
}
declare module 'react-animations/lib/hinge.js' {
  declare module.exports: $Exports<'react-animations/lib/hinge'>;
}
declare module 'react-animations/lib/index.js' {
  declare module.exports: $Exports<'react-animations/lib/index'>;
}
declare module 'react-animations/lib/jello.js' {
  declare module.exports: $Exports<'react-animations/lib/jello'>;
}
declare module 'react-animations/lib/light-speed-in.js' {
  declare module.exports: $Exports<'react-animations/lib/light-speed-in'>;
}
declare module 'react-animations/lib/light-speed-out.js' {
  declare module.exports: $Exports<'react-animations/lib/light-speed-out'>;
}
declare module 'react-animations/lib/lightSpeedIn.js' {
  declare module.exports: $Exports<'react-animations/lib/lightSpeedIn'>;
}
declare module 'react-animations/lib/lightSpeedOut.js' {
  declare module.exports: $Exports<'react-animations/lib/lightSpeedOut'>;
}
declare module 'react-animations/lib/merge.js' {
  declare module.exports: $Exports<'react-animations/lib/merge'>;
}
declare module 'react-animations/lib/pulse.js' {
  declare module.exports: $Exports<'react-animations/lib/pulse'>;
}
declare module 'react-animations/lib/roll-in.js' {
  declare module.exports: $Exports<'react-animations/lib/roll-in'>;
}
declare module 'react-animations/lib/roll-out.js' {
  declare module.exports: $Exports<'react-animations/lib/roll-out'>;
}
declare module 'react-animations/lib/rollIn.js' {
  declare module.exports: $Exports<'react-animations/lib/rollIn'>;
}
declare module 'react-animations/lib/rollOut.js' {
  declare module.exports: $Exports<'react-animations/lib/rollOut'>;
}
declare module 'react-animations/lib/rotate-in-down-left.js' {
  declare module.exports: $Exports<'react-animations/lib/rotate-in-down-left'>;
}
declare module 'react-animations/lib/rotate-in-down-right.js' {
  declare module.exports: $Exports<'react-animations/lib/rotate-in-down-right'>;
}
declare module 'react-animations/lib/rotate-in-up-left.js' {
  declare module.exports: $Exports<'react-animations/lib/rotate-in-up-left'>;
}
declare module 'react-animations/lib/rotate-in-up-right.js' {
  declare module.exports: $Exports<'react-animations/lib/rotate-in-up-right'>;
}
declare module 'react-animations/lib/rotate-in.js' {
  declare module.exports: $Exports<'react-animations/lib/rotate-in'>;
}
declare module 'react-animations/lib/rotate-out-down-left.js' {
  declare module.exports: $Exports<'react-animations/lib/rotate-out-down-left'>;
}
declare module 'react-animations/lib/rotate-out-down-right.js' {
  declare module.exports: $Exports<'react-animations/lib/rotate-out-down-right'>;
}
declare module 'react-animations/lib/rotate-out-up-left.js' {
  declare module.exports: $Exports<'react-animations/lib/rotate-out-up-left'>;
}
declare module 'react-animations/lib/rotate-out-up-right.js' {
  declare module.exports: $Exports<'react-animations/lib/rotate-out-up-right'>;
}
declare module 'react-animations/lib/rotate-out.js' {
  declare module.exports: $Exports<'react-animations/lib/rotate-out'>;
}
declare module 'react-animations/lib/rotateIn.js' {
  declare module.exports: $Exports<'react-animations/lib/rotateIn'>;
}
declare module 'react-animations/lib/rotateInDownLeft.js' {
  declare module.exports: $Exports<'react-animations/lib/rotateInDownLeft'>;
}
declare module 'react-animations/lib/rotateInDownRight.js' {
  declare module.exports: $Exports<'react-animations/lib/rotateInDownRight'>;
}
declare module 'react-animations/lib/rotateInUpLeft.js' {
  declare module.exports: $Exports<'react-animations/lib/rotateInUpLeft'>;
}
declare module 'react-animations/lib/rotateInUpRight.js' {
  declare module.exports: $Exports<'react-animations/lib/rotateInUpRight'>;
}
declare module 'react-animations/lib/rotateOut.js' {
  declare module.exports: $Exports<'react-animations/lib/rotateOut'>;
}
declare module 'react-animations/lib/rotateOutDownLeft.js' {
  declare module.exports: $Exports<'react-animations/lib/rotateOutDownLeft'>;
}
declare module 'react-animations/lib/rotateOutDownRight.js' {
  declare module.exports: $Exports<'react-animations/lib/rotateOutDownRight'>;
}
declare module 'react-animations/lib/rotateOutUpLeft.js' {
  declare module.exports: $Exports<'react-animations/lib/rotateOutUpLeft'>;
}
declare module 'react-animations/lib/rotateOutUpRight.js' {
  declare module.exports: $Exports<'react-animations/lib/rotateOutUpRight'>;
}
declare module 'react-animations/lib/rubber-band.js' {
  declare module.exports: $Exports<'react-animations/lib/rubber-band'>;
}
declare module 'react-animations/lib/rubberBand.js' {
  declare module.exports: $Exports<'react-animations/lib/rubberBand'>;
}
declare module 'react-animations/lib/shake.js' {
  declare module.exports: $Exports<'react-animations/lib/shake'>;
}
declare module 'react-animations/lib/slide-in-down.js' {
  declare module.exports: $Exports<'react-animations/lib/slide-in-down'>;
}
declare module 'react-animations/lib/slide-in-left.js' {
  declare module.exports: $Exports<'react-animations/lib/slide-in-left'>;
}
declare module 'react-animations/lib/slide-in-right.js' {
  declare module.exports: $Exports<'react-animations/lib/slide-in-right'>;
}
declare module 'react-animations/lib/slide-in-up.js' {
  declare module.exports: $Exports<'react-animations/lib/slide-in-up'>;
}
declare module 'react-animations/lib/slide-out-down.js' {
  declare module.exports: $Exports<'react-animations/lib/slide-out-down'>;
}
declare module 'react-animations/lib/slide-out-left.js' {
  declare module.exports: $Exports<'react-animations/lib/slide-out-left'>;
}
declare module 'react-animations/lib/slide-out-right.js' {
  declare module.exports: $Exports<'react-animations/lib/slide-out-right'>;
}
declare module 'react-animations/lib/slide-out-up.js' {
  declare module.exports: $Exports<'react-animations/lib/slide-out-up'>;
}
declare module 'react-animations/lib/slideInDown.js' {
  declare module.exports: $Exports<'react-animations/lib/slideInDown'>;
}
declare module 'react-animations/lib/slideInLeft.js' {
  declare module.exports: $Exports<'react-animations/lib/slideInLeft'>;
}
declare module 'react-animations/lib/slideInRight.js' {
  declare module.exports: $Exports<'react-animations/lib/slideInRight'>;
}
declare module 'react-animations/lib/slideInUp.js' {
  declare module.exports: $Exports<'react-animations/lib/slideInUp'>;
}
declare module 'react-animations/lib/slideOutDown.js' {
  declare module.exports: $Exports<'react-animations/lib/slideOutDown'>;
}
declare module 'react-animations/lib/slideOutLeft.js' {
  declare module.exports: $Exports<'react-animations/lib/slideOutLeft'>;
}
declare module 'react-animations/lib/slideOutRight.js' {
  declare module.exports: $Exports<'react-animations/lib/slideOutRight'>;
}
declare module 'react-animations/lib/slideOutUp.js' {
  declare module.exports: $Exports<'react-animations/lib/slideOutUp'>;
}
declare module 'react-animations/lib/swing.js' {
  declare module.exports: $Exports<'react-animations/lib/swing'>;
}
declare module 'react-animations/lib/tada.js' {
  declare module.exports: $Exports<'react-animations/lib/tada'>;
}
declare module 'react-animations/lib/types.js' {
  declare module.exports: $Exports<'react-animations/lib/types'>;
}
declare module 'react-animations/lib/utils.js' {
  declare module.exports: $Exports<'react-animations/lib/utils'>;
}
declare module 'react-animations/lib/wobble.js' {
  declare module.exports: $Exports<'react-animations/lib/wobble'>;
}
declare module 'react-animations/lib/zoom-in-down.js' {
  declare module.exports: $Exports<'react-animations/lib/zoom-in-down'>;
}
declare module 'react-animations/lib/zoom-in-left.js' {
  declare module.exports: $Exports<'react-animations/lib/zoom-in-left'>;
}
declare module 'react-animations/lib/zoom-in-right.js' {
  declare module.exports: $Exports<'react-animations/lib/zoom-in-right'>;
}
declare module 'react-animations/lib/zoom-in-up.js' {
  declare module.exports: $Exports<'react-animations/lib/zoom-in-up'>;
}
declare module 'react-animations/lib/zoom-in.js' {
  declare module.exports: $Exports<'react-animations/lib/zoom-in'>;
}
declare module 'react-animations/lib/zoom-out-down.js' {
  declare module.exports: $Exports<'react-animations/lib/zoom-out-down'>;
}
declare module 'react-animations/lib/zoom-out-left.js' {
  declare module.exports: $Exports<'react-animations/lib/zoom-out-left'>;
}
declare module 'react-animations/lib/zoom-out-right.js' {
  declare module.exports: $Exports<'react-animations/lib/zoom-out-right'>;
}
declare module 'react-animations/lib/zoom-out-up.js' {
  declare module.exports: $Exports<'react-animations/lib/zoom-out-up'>;
}
declare module 'react-animations/lib/zoom-out.js' {
  declare module.exports: $Exports<'react-animations/lib/zoom-out'>;
}
declare module 'react-animations/lib/zoomIn.js' {
  declare module.exports: $Exports<'react-animations/lib/zoomIn'>;
}
declare module 'react-animations/lib/zoomInDown.js' {
  declare module.exports: $Exports<'react-animations/lib/zoomInDown'>;
}
declare module 'react-animations/lib/zoomInLeft.js' {
  declare module.exports: $Exports<'react-animations/lib/zoomInLeft'>;
}
declare module 'react-animations/lib/zoomInRight.js' {
  declare module.exports: $Exports<'react-animations/lib/zoomInRight'>;
}
declare module 'react-animations/lib/zoomInUp.js' {
  declare module.exports: $Exports<'react-animations/lib/zoomInUp'>;
}
declare module 'react-animations/lib/zoomOut.js' {
  declare module.exports: $Exports<'react-animations/lib/zoomOut'>;
}
declare module 'react-animations/lib/zoomOutDown.js' {
  declare module.exports: $Exports<'react-animations/lib/zoomOutDown'>;
}
declare module 'react-animations/lib/zoomOutLeft.js' {
  declare module.exports: $Exports<'react-animations/lib/zoomOutLeft'>;
}
declare module 'react-animations/lib/zoomOutRight.js' {
  declare module.exports: $Exports<'react-animations/lib/zoomOutRight'>;
}
declare module 'react-animations/lib/zoomOutUp.js' {
  declare module.exports: $Exports<'react-animations/lib/zoomOutUp'>;
}
declare module 'react-animations/webpack.config.js' {
  declare module.exports: $Exports<'react-animations/webpack.config'>;
}
