// flow-typed signature: 4a8d478dac91f83a3270e6e2db4a4c06
// flow-typed version: <<STUB>>/sanitize.css_v6.0.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sanitize.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sanitize.css' {
  declare module.exports: any;
}
