// flow-typed signature: 35a14984db6a8f5f44d85c583c89b8cf
// flow-typed version: <<STUB>>/sanitize.css_v^5.0.0/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sanitize.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sanitize.css' {
  declare module.exports: any;
}
