// flow-typed signature: ac5e5c6d9a4dc1184dca692e1b5c33b8
// flow-typed version: <<STUB>>/sanitize.css_v6.0.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sanitize.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sanitize.css' {
  declare module.exports: any;
}
